name: Build and Publish Docker image

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Set environment based on branch
        id: envvars
        run: |
          TAG="${{ steps.vars.outputs.TAG }}"
          if [[ "$TAG" == "main" ]]; then
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> $GITHUB_ENV
          else
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_STAGING_API_URL }}" >> $GITHUB_ENV
          fi
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME_LC=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          TAG=${{ steps.vars.outputs.TAG }}

          docker build \
            --build-arg NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL \
            -t "$IMAGE_NAME_LC:$TAG" .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME_LC=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          TAG=${{ steps.vars.outputs.TAG }}

          docker push "$IMAGE_NAME_LC:$TAG"
